
sequence = "TGACGACGCAGCAGTGCTTTTGGCAAACCCTTGGTTAAGCAGACACTTGACCCTAAGCGCAGGCAGATGTCACCAAATATCTGCCCTTGGGTCCAGGGCCGAAGGGTCTCAAACCAGAACTAGCCCATTGAGCCTTTATCAAGACTACCTACAGAAGACCGGGCCCTATCTAATAGAGAACGCCGAGTGAAACCGGGTCTAGGAGACTTCTGGACGCGGAGAAGCGGATTCTCGAGCCCGTTCTCTCGGACGAAATCATGCCCCTTGGCAATTACCAGCAAACCCTACGATAGCCTTGGAGCTTCTGTTCGGACTGCGGGAAAGTGCTAGTTAGATATACAATGGATTTTGGCGGGGATGGTCGCGTTCCCCGGGGGCATAGCACTGCGAAAAGGTATCGTTTGCTAATCAAGTAAAATGACTGCGAGTAGTGCACGCTCGCCCAAGTTGCACAGTAATCACTATACGACAGCCTCGGGACACTGCGGTTGATGTGAGGCTCTAGCTCCTAGCCTTACTGCGAGTATAATAATGTATATACCCTACTTGATTTACAGGATCTTTACCAATGAGGAGGGGCGATCGTAACTAATAATATCTGGGTAGAGGTGTCGCACCACTTCATCGCTGTCCCCGTTACTACCTTGCACTAATTGCAGCTCGGTAACCCCATCGAAGCGCCGTTTCATACGCAAGCGAAGTATGGGGCGACGACAAAAAAAATGCTCGAGGTGGACACAGTGGAACGCCGCCTCTCCTGTTGCGACATTAAATTGTGGGAGCTCATGCGCATTATCCGTATCCATCGCGGCACGGAGAAAGGAGTACGCAGGTTGGCGTCTTCAATCGGTGTTACTTGCGC"


adenine = 0
cytosine = 0
guanine = 0
thymine = 0


for nucleotide in sequence:
    if nucleotide == 'A':
        adenine += 1
    elif nucleotide == 'T':
        thymine +=1
    elif nucleotide == 'C':
        cytosine += 1
    elif nucleotide == 'G':
        guanine += 1
     
print (str(adenine) + " " + str(cytosine) + " " + str(guanine) + " " + str(thymine))
       



